int= int(10)

floatToInt= int(10.4)
strToInt= int("10")
print(int)
print(floatToInt)
print(strToInt)
intToFloat=float(10)
float=float(10.4)
strToFloat= float("10")
print(intToFloat)
print(float)
print(strToFloat)
intToStr=str(10)
floatToStr=str(10.4)
str=str("10")
print(intToStr)
print(floatToStr)
print(str)